### PR TITLE
Update install.yml

### PR DESCRIPTION
**Pull request by fredrikhgrelland**

### CODE REVIEW

**Comment by fredrikhgrelland** [comment]
Works

**Comment by zhenik** [comment]
> Works

Could you elaborate a bit more, was it just a typo? I have read the original question, is the answer `Side effect, and should not be there.`.

**Comment by Neha-Sinha2305** [comment]
I checked the logs and this seem to work. I wonder if it is just a hack to fix the issue!

**Comment by fredrikhgrelland** [comment]
It is a side effect of the way I set variables. Bash reads each line into the p variable and then evaluates. Since we ‘set -a’ ALL variables will be exported, including p, which ends up being blank. By unsetting it after use, we remove this from out exported variables

**Pull request merged**
