### PR TITLE
Linting for TF files + documentation

### LINKED ISSUE #301: Linter for `tf` files
- [ ] Linter for `tf` files
- [ ] script running before commits -> `terraform fmt -recursive` (research)

### PR DESCRIPTION
**Pull request by pdmthorsrud**
closes #301

### CODE REVIEW

**Comment by zhenik** [comment]
I have feeling that after this PR, we go fixing modules :)

**Review by zhenik — APPROVED** [review]

**Comment by pdmthorsrud** [comment]
> I have feeling that after this PR, we go fixing modules :)

I do believe you've got a point haha

**Review by claesgill — APPROVED** [review]
LGTM :rocket:

**Comment by claesgill** [comment]
Would it be possible to test the tf-linter locally? In the same way as `make linter`.

**Comment by pdmthorsrud** [comment]
> Would it be possible to test the tf-linter locally? In the same way as `make linter`.

[You could run super-linter locally](https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md) (which is the one we use). I am _not_ sure if it picks up our "custom" rules though (which is under `/.github/linters`), I haven't tested it. Maybe we should add some make targets to run linters, that would be very nice.

**Pull request merged**
