### PR TITLE
Adding versions section to readme

### LINKED ISSUE #358: Add section `version` to README
## Version
| vagrant-hashistack | consul | nomad  | vault  | consul-template |
| ------------- |:-------------|:-------------|:-------------|:-------------|
| 0.4.3      | 1.8.4      |   0.12.4 |  1.5.3 |  0.25.1 | 
| 0.4.0      | 1.8.3 | 0.12.3 |1.5.2 | 0.25.1 |

Might need to expand columns. Also, having such a table either at the beginning or end of the documentation

### PR DESCRIPTION
**Pull request by claesgill**
Closes #358 

Can someone please help me fill in the versions where the :shrug:-emoji is? I'm not able to use the box from my private mac 😅

### CODE REVIEW

**Comment by pdmthorsrud** [comment]
Enterprise versions do not follow the releases of OSS versions, do they? I couldn't really find anything online

**Review by zhenik — APPROVED** [review]

**Comment by fredrikhgrelland** [comment]
@pdmthorsrud They do

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud They do

Never mind then!

**Review by pdmthorsrud — APPROVED** [review]
LGTM

**Comment by claesgill** [comment]
Appreciate the help folks👌

**Pull request merged**
