### PR TITLE
Dev templates

### LINKED ISSUE #83: Add skeleton project - **a starting point** - for using the vagrant box in a project for test and dev
In addition to strong documentation on how to use the box and customize to fit the needs of a project, we could simplify the process of building a CI pipeline backed by `vagrant-hashistack` by adding a skeleton project.

### If put in a separate repo e.g. `vagrant-hashistack-template`
- 👍 Merging in changes directly whenever you would like to use new or changed features to the box.
- 👍 Less need to document what needs to happen if you move from one version to another as it is implicit in the diff.
- 👍 Fork the repository - quickstart.
- 👎 It requires cross repo PRs to be synced as well as release cadence.

### If put in a sub directory `/template/*/`
- 👍 We could add different templates for different needs. ( dev/test/demo)
- 👎 It will require a series of git commandline actions in order to be easily consumed and updated to new versions.
- 👍 All PRs will include any changes to templates. Simplify dev process.

### PR DESCRIPTION
**Pull request by fredrikhgrelland**
close #83

### CODE REVIEW

**Comment by zhenik** [comment]
Could you update `Makefile` in the root? 
Remove all commands which are related to vagrant (make up, make test, etc...)

**Comment by zhenik** [comment]
I run `make up` from `~/template/dev`

```
TASK [Wait for nomad to start] *************************************************
FAILED - RETRYING: Wait for nomad to start (60 retries left).
....
FAILED - RETRYING: Wait for nomad to start (5 retries left).
FAILED - RETRYING: Wait for nomad to start (4 retries left).
FAILED - RETRYING: Wait for nomad to start (3 retries left).
FAILED - RETRYING: Wait for nomad to start (2 retries left).
FAILED - RETRYING: Wait for nomad to start (1 retries left).
fatal: [default]: FAILED! => {
    "attempts": 60,
    "changed": false,
    "content": "",
    "elapsed": 0,
    "redirected": false,
    "status": -1,
    "url": "http://127.0.0.1:4646/v1/jobs"
}

MSG:

Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>

PLAY RECAP *********************************************************************
default                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
make: *** [up] Error 1
```

```
 vagrant global-status                                                                                                                          ✔  19:41:14 
id       name    provider   state   directory                                                           
--------------------------------------------------------------------------------------------------------
38b04a6  default virtualbox running /Users/zhenik/src/github.com/zhenik/vagrant-hashistack/template/dev
```

**Comment by fredrikhgrelland** [comment]
@zhenik Did you build first? Make build

**Comment by fredrikhgrelland** [comment]
> Could you update `Makefile` in the root?
> Remove all commands which are related to vagrant (make up, make test, etc...)

Not all commands should or can be removed. `test` and `build` are used still. https://github.com/fredrikhgrelland/vagrant-hashistack/pull/93/commits/9708e2b6148f35ad0eb9999eb065965ff33b013d removes `up` and `down`. We should follow up on moving installation intothe templates in a separate Makefile

**Pull request merged**
