### PR TITLE
Make the bootstrap process idempotent

### LINKED ISSUE #234: Make the bootstrap process idempotent
The bootstrap-process will fail if it has already run once. This should rather just skip steps that are already done (for example running `nomad acl bootstrap`), and carry on with other tasks.

### PR DESCRIPTION
**Pull request by Neha-Sinha2305**
I have tried to solve this issue by making use of custom facts in ansible. There surely would be a better way to fix this and so i am open to suggestions :)
closes #234

### CODE REVIEW

**Comment by zhenik** [comment]
@Neha-Sinha2305 Could you provide any links or explain how this implementation works (I guess it should be connected with ansible fact-files).

As far as I understood:

You store the state (like event happened) as a custom variable in file (e.g. /etc/ansible/facts.d/nomad_acl.fact). 

And then, it parses the correct way by ansible here
```yaml
bool and ansible_local.nomad.vault_integration.completed is not defined
```

**Comment by pdmthorsrud** [comment]
This task
https://github.com/Neha-Sinha2305/vagrant-hashistack/blob/ea61618e1df40f5023846ea217314fb4c853c59e/ansible/bootstrap.yml#L45-L51
is technically a one and done, but does no harm by running several times. Could we maybe add the extra conditional on this as well, just for clarity's sake. The way it's presented it looks like a task that _ should_ run every time, which is confusing.

**Review by pdmthorsrud — CHANGES_REQUESTED** [review]
https://github.com/Neha-Sinha2305/vagrant-hashistack/blob/ea61618e1df40f5023846ea217314fb4c853c59e/ansible/bootstrap.yml#L45-L51

I can't suggest changes because it's not part of any changes in PR, but this code _can_ be run every time without harm, but is technically a one and done, that should only be run the first time, just for clarity's sake I think.

**Comment by Neha-Sinha2305** [comment]
> @Neha-Sinha2305 Could you provide any links or explain how this implementation works (I guess it should be connected with ansible fact-files).
> 
> As far as I understood:
> 
> You store the state (like event happened) as a custom variable in file (e.g. /etc/ansible/facts.d/nomad_acl.fact).
> 
> And then, it parses the correct way by ansible here
> 
> ```yaml
> bool and ansible_local.nomad.vault_integration.completed is not defined
> ```
Yeah, that's right!
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#local-facts-facts-d

**Comment by zhenik** [comment]
@Neha-Sinha2305 we probably need documentation for this

**Review by zhenik — APPROVED** [review]

**Comment by Neha-Sinha2305** [comment]
> https://github.com/Neha-Sinha2305/vagrant-hashistack/blob/ea61618e1df40f5023846ea217314fb4c853c59e/ansible/bootstrap.yml#L45-L51
> 
> I can't suggest changes because it's not part of any changes in PR, but this code _can_ be run every time without harm, but is technically a one and done, that should only be run the first time, just for clarity's sake I think.

So, should i add the fact check for these two tasks as well? 
Surely it makes sense to run these only once but since they do not create any issue so we could avoid adding extra lines of code that will flow in with the fact check code.

**Comment by pdmthorsrud** [comment]
> > https://github.com/Neha-Sinha2305/vagrant-hashistack/blob/ea61618e1df40f5023846ea217314fb4c853c59e/ansible/bootstrap.yml#L45-L51
> > I can't suggest changes because it's not part of any changes in PR, but this code _can_ be run every time without harm, but is technically a one and done, that should only be run the first time, just for clarity's sake I think.
> 
> So, should i add the fact check for these two tasks as well?
> Surely it makes sense to run these only once but since they do not create any issue so we could avoid adding extra lines of code that will flow in with the fact check code.

That's a fair point. I don't have any clear preference for either, so I'm approving! :)

**Review by pdmthorsrud — APPROVED** [review]

**Pull request merged**
