### PR TITLE
Code fixes to run 'vagrant up' command locally without extra vars

### LINKED ISSUE #374: Make it possible to run box with `vagrant up`
Right now you need to add the tag local-test=true or run `--skip-tags test` to get past the env_override. Find a way to circumvent this.
Below is from a run with `vagrant up`
image

Offending lines: 
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/47d38018a42aa57fbd99ee2e4c3d3b5c8fc70155/ansible/bootstrap.yml#L11-L15

### PR DESCRIPTION
**Pull request by Neha-Sinha2305**
closes #374 
This requires  changes in [template/Makefile](https://github.com/fredrikhgrelland/vagrant-hashistack-template/blob/master/Makefile) so I will add a PR in vagrant-hashistack-template repo to support the changes done here.

### CODE REVIEW

**Comment by Neha-Sinha2305** [comment]
I need https://github.com/fredrikhgrelland/vagrant-hashistack-template/pull/39 to be reviewed and merged to test the fixes done here.

**Review by pdmthorsrud — DISMISSED** [review]
LGTM

**Comment by zhenik** [comment]
@Neha-Sinha2305 do we need to update documentation in this section https://github.com/fredrikhgrelland/vagrant-hashistack#option-1-starting-a-plain-default-box ?

**Comment by Neha-Sinha2305** [comment]
> @Neha-Sinha2305 do we need to update documentation in this section https://github.com/fredrikhgrelland/vagrant-hashistack#option-1-starting-a-plain-default-box ?

Yep...I have updated the documentation likewise : https://github.com/Neha-Sinha2305/vagrant-hashistack/tree/ci_improvements#option-1-starting-a-plain-default-box

[PR-README-changes](https://github.com/fredrikhgrelland/vagrant-hashistack/pull/378/files#diff-04c6e90faac2675aa89e2176d2eec7d8L301)

**Review by zhenik — APPROVED** [review]

**Review by zhenik — APPROVED** [review]

**Comment by Neha-Sinha2305** [comment]
The test has [failed](https://github.com/fredrikhgrelland/vagrant-hashistack/pull/378/checks?check_run_id=1220806599#step:9:105) as expected. 
I had on purpose changed the **.env_override file path** in the workflow file so that it does not get sourced and so **TF_VAR_env_override** is not set to true. This was done as part of **negative testing**.
I will revert the changes in the workflow file and the tests in the next commit should pass.

**Comment by Neha-Sinha2305** [comment]
As expected the tests are green now. Need one approval before i could go ahead with merging it to master.

**Review by zhenik — APPROVED** [review]

**Pull request merged**
